[package]
authors = ["Hee Suk Shin <heesuk@gmail.com>"]
name = "mvpcore"
version = "0.1.0"

[dependencies]
libc = "0.2.42"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
sqlite3 = "0.24.0"

[lib]
crate-type = ["staticlib"]
