[package]
authors = ["Hee Suk Shin <heesuk@gmail.com>"]
name = "mvpcore"
version = "0.1.0"

[dependencies]
dirs = "1.0.3"
libc = "0.2.43"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
sqlite3 = "0.24.0"

[lib]
crate-type = ["staticlib"]
